name: Latest blog post workflow
on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.joehxblog.com/feed.xml"
          comment_tag_name: "JOEHXBLOG"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.puppy-snuggles.com/feed.xml"
          comment_tag_name: "PUPPY-SNUGGLES"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://news.puppy-snuggles.com/feed"
          comment_tag_name: "PUPPY-SNUGGLES-NEWS"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.reddit.com/user/joehx/.rss"
          comment_tag_name: "REDDIT"
